Logs update

diff --git a/roles/logs_server/templates/logstoprm_staging.sh.j2 b/roles/logs_server/templates/logstoprm_staging.sh.j2
--- a/roles/logs_server/templates/logstoprm_staging.sh.j2
+++ b/roles/logs_server/templates/logstoprm_staging.sh.j2
@@ -1,4 +1,10 @@
 #!/bin/bash
+# {% raw %}
+
+set -eE
+trap 'logger -t logstoprm-cron "The command (${BASH_COMMAND}) had failed on fine number (${LINENO})"' ERR
+
+{% endraw %}
 
 destination_dir="{{ logstoprm.rsyncd_dir }}"
 
@@ -16,19 +22,29 @@ test -d "${destination_dir}" || \
 # main
 cd "${source_dir}"
 
-# - copy, don't move the files
-# - change the ownership
-# - ignore files smaller than 20byes as they are compressed empty files (plus
+# - find compressed files older than 7 days
+# - ignore files smaller than 20-bytes as they are compressed empty files (plus
 #   20 bytes can not contain enough information to help with anything)
-# - copy only files older than 7 days
-# - change ownership: owner=root and group=logstoprm
-# - change permissions for group to read-only
-find ./ -type f -mtime +7 -exec rsync -aR --min-size=21 --chown=root:{% endraw %}{{ logstoprm.group }}{% raw %} --chmod=D750,F640 ./{} /mnt/logstoprm/ \;
-
-#rsync -ar --min-size=21 --chown=root:{% endraw %}{{ logstoprm.group }}{% raw %} --chmod=D750,F640 ${source_dir}/./ ${destination_dir}
-#find . -size +21c -type f -name "*.gz" \
-#   -exec rsync --chown root:{% endraw %}{{ logstoprm.group }}{% raw %} --chmod=D750,F640 {} ${destination_dir} \; \
-#find . -type d -exec chown root:{% endraw %}{{ logstoprm.group }}{% raw %} -R 750 ${destination_dir} \;
+# - move them (that is: copy and then delete)
+# - and change ownership: owner=root and group=logstoprm
+# - and change permissions for user and group to be able to read-only
+# find flags
+#   --remove-source-files  after they have been successfully copied
+#   -R use                 relative path-names
+#   +21c                   more than 21 characters (bytes)
+# rsync flags
+#   --ignore-existing      don't update files if they already exist on destination
+logger -t logstoprm "Starting to move log files to ${destination_dir}"
+find ./ -type f -size +21c -mtime +7 -name "*.gz" -exec rsync \
+   --remove-source-files --ignore-existing -a -R --min-size=21 \
+   --chown=root:{% endraw %}{{ logstoprm.group }}{% raw %} \
+   --chmod=D750,F640 ./{} /mnt/logstoprm/ 2>>${0}.logs \;
+if [[ "$?" -eq "0" ]]; then
+   logger -t logstoprm "Logs have been successfully moved"
+else
+   logger -t logstoprm "There has been error while moving logs"
+fi
+   
 
 # the folder are created while copying, so permissions need to be additionally fixed
 cd ${destination_dir}
