Logtoprm: improved cron script

diff --git a/roles/logs_toprm/templates/logstoprm_cron.sh.j2 b/roles/logs_toprm/templates/logstoprm_cron.sh.j2
--- a/roles/logs_toprm/templates/logstoprm_cron.sh.j2
+++ b/roles/logs_toprm/templates/logstoprm_cron.sh.j2
@@ -30,9 +30,9 @@ trap 'logger -t "${_log_tag}" "Command (${BASH_COMMAND}) has failed on line numb
 #
 
 _lock_dirs="{% endraw %}{{ logs_toprm_destination }}{% raw%}/lock_dirs"      # full path
-if ! test -d "${_lock_dirs}"; then mkdir -p ${_lock_dirs}; fi
+if ! test -d "${_lock_dirs}"; then mkdir -p ${_lock_dirs}; logger -t "${_log_tag}" "Created {_lock_dirs}"; fi
 _hostname="${1:-$(/bin/hostname)}"
-_small_delay="30"       # [seconds] how long should cron wait (after lock directory is created) to start the process
+_small_delay="3"       # [seconds] how long should cron wait (after lock directory is created) to start the process
 _max_runtime=36000      # [seconds] how long can cron job run before being killed?
              # ^8h      # Should be less than time between to cron exections. If daily cron (86400s)
                         # then 80000 is appropriate. Note that the jobs can run longes, as _max_loop is
@@ -45,7 +45,8 @@ _max_remote_time=21600  # [seconds] how long should current cron ignore the cron
 # placeholder variables to be later populated
 _earl_name=''
 # the main command we would like to run inside cron
-_command="echo rsync -a --rsh=\"ssh -l {% endraw %}{{ logs_toprm_earl_user }}{% raw%}\" ${_earl_name}::logstoprm {% endraw %}{{ logs_toprm_destination }}{% raw%}/${_earl_name}"
+_command="sleep 100"
+#echo rsync -a --rsh=\"ssh -l {% endraw %}{{ logs_toprm_earl_user }}{% raw%}\" ${_earl_name}::logstoprm {% endraw %}{{ logs_toprm_destination }}{% raw%}/${_earl_name}"
 
 _script_path_dir="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
 
@@ -111,7 +112,7 @@ function killing_pid(){                                                       # 
       exit 255
    fi
    for _each_pid in ${_pids}; do
-      if ps -u ${USER} -U ${USER} -o pid | grep ${_each_pid}; then
+      if pgrep -u ${UID} timeout 2>&1 | grep -q ${_each_pid}; then  # killing timeout processes
          logger -t "${_log_tag}" "Killing process ${_each_pid}"
          kill -9 ${_each_pid} && \
            logger -t "${_log_tag}" "  ${_each_pid} - process killed!"
@@ -120,31 +121,31 @@ function killing_pid(){                                                       # 
 }
 
 function start_flow(){
-   logger -t "${_log_tag}" "Starting main function"
+   logger -t "${_log_tag}" "Entering main loop (for ${_earl_name})"
    sync
    cd ${_script_path_dir}
    if ! test -w ${_lock_dirs}/; then
-      logger -t "${_log_tag}" "Main locking directory is missing: ${_lock_dirs}"
+      logger -t "${_log_tag}" "(main)${_earl_name}  - top level locking directory is missing - ${_lock_dirs}"
    fi
    _all_host_count=$(ls -1 ${_lock_dirs} | wc -l)
    cd ${_lock_dirs}
    _my_hostname_count=$(find . -name "${_hostname}" | wc -l)
    _lock_dir="${_hostname}"
    if [[ "${_all_host_count}" -eq "0" ]]; then
-      logger -t "${_log_tag}" " - no other host if running anything right now"
-      logger -t "${_log_tag}" "   - making lock directory ${_lock_dir}"
-      mkdir "${_lock_dir}" || { logger -t "${_log_tag}" "   - cannot create lock dir ${_lock_dir}" ; exit 255; }
+      logger -t "${_log_tag}" "(main)${_earl_name}  - no other host if running anything right now"
+      logger -t "${_log_tag}" "(main)${_earl_name}  - making lock directory ${_lock_dir}"
+      mkdir "${_lock_dir}" || { logger -t "${_log_tag}" "(main)${_earl_name}    - cannot create lock dir ${_lock_dir}" ; exit 255; }
       sync
       sleep ${_small_delay}                                                 # don't rush things
       start_flow
    else                                                                       # hosts are running things
-      logger -t "${_log_tag}" " - there are lock directories"
+      logger -t "${_log_tag}" "(main)${_earl_name}  - there are SOME lock dirs"
       if [[ "${_my_hostname_count}" -gt "0" ]]; then
-         logger -t "${_log_tag}" " - this hostname is supposed to be running the command right now"
+         logger -t "${_log_tag}" "(main)${_earl_name}  - this hostname is supposed to be running the command right now"
          if [[ "${_my_hostname_count}" -eq "${_all_host_count}" ]]; then              # it's only my hostname
-            logger -t "${_log_tag}" " - great, ONLY this hostname is supposed to be running the command right now"
+            logger -t "${_log_tag}" "(main)${_earl_name}  - ONLY this hostname is supposed to be running the command right now"
             if check_time ; then
-               logger -t "${_log_tag}" " - start delay is correct ... can proceed"
+               logger -t "${_log_tag}" "(main)${_earl_name}  - we already delayed the start so we can now proceed"
                _pidfile="${_hostname}/pid"
                # Is pid file inside and it contains pid?
                if test -e "${_pidfile}" && test -n "$(cat ${_pidfile})" ; then   # pidfile exists and is not empty
@@ -152,68 +153,63 @@ function start_flow(){
                   _pidfile_nr_lines="$(wc -l < "${_pidfile}")"
                   if [[ "${_pidfile_nr_lines}" -ge "${_max_loops}" ]]; then   # we found this process running too many times, time to kill it
                      killing_pid
-                     remove_locks
                   else                                                        # it exist and has a pid
-                     logger -t "${_log_tag}" " - the process is already running > let's log this and exit"
+                     logger -t "${_log_tag}" "(main)${_earl_name}  - the process is already running > let's log this and exit"
                      echo "${_running_pid}" >> "${_pidfile}"                  # duplicating process ID inside pid file
                   fi
                else                                                           # we start the process
                   # Executing the main command
-                  logger -t "${_log_tag}" "     - yes, let's run the main command"
-                  { "${_command}" & }; _child="${!}"
+                  logger -t "${_log_tag}" "(main)${_earl_name}  - RUNNING MAIN COMMAND"
+                  { "timeout ${_max_runtime} ${_command}" & }; _child="${!}"
                   echo "${_child}" >> "${_pidfile}"                           # storing process ID inside the pid file
-                  # Next line ensures that process does not run longer than allowed
-                  { ( sleep "${_max_runtime}"; \
-                      logger -t "${_log_tag}" "Killing PID ${_child} due to running for too long!"; \
-                      killing_pid "${_child}"; \
-                  ) & } 1>/dev/null 2>&1
-        # Next line ensures that process is killed if lock directory disappears
-        { ( while test -d ${_lock_dir}; do sleep ${_small_delay}; done; \
-            logger -t "${_log_tag}" "Killing PID ${_child} because the lock dir disappeared!"; \
-                      killing_pid "${_child}"; \
-                  ) & } 1>/dev/null 2>&1
-        wait ${_child} 2>/dev/null || true                          # true ensures that the cleanup is done
-                  remove_locks                                                # remove the lock files and directories
-                  exit 0                                                      # job successfully finished
+                  # Next line ensures that process is killed if lock directory disappears
+                  {  (  while test -d ${_lock_dir}; do sleep ${_small_delay}; done; \
+                        if pgrep -u ${UID} timeout 2>&1 | grep -q ${_child}; then 
+                           logger -t "${_log_tag}" "(main)${_earl_name} Killing PID ${_child} because the lock dir disappeared!"; \
+                           killing_pid "${_child}"; \
+                        fi \
+                     ) & \
+                  } 1>/dev/null 2>&1
+                  wait ${_child} 2>/dev/null || true                          # true ensures that the cleanup is done
                fi
             else
                check_time || case ${?} in
                   1)
-                     logger -t "${_log_tag}" "     - too early, let's wait ... "
+                     logger -t "${_log_tag}" "(main)${_earl_name}    - too early, let's wait ... "
                      sleep ${_small_delay} && start_flow         # go to start
                      ;;
                   13|14)
-                     logger -t "${_log_tag}" "     - we should kill: this process is running for too long"
+                     logger -t "${_log_tag}" "(main)${_earl_name}    - we should kill: this process is running for too long"
                      killing_pid
-                     remove_locks
                      ;;
                   255)
-                     logger -t "${_log_tag}" "Cannot get time of lock directory!"
+                     logger -t "${_log_tag}" "(main)${_earl_name} Cannot get time of lock directory!"
                      exit 255
                      ;;
                   *)
-                     logger -t "${_log_tag}" "Unknown error, should log"
+                     logger -t "${_log_tag}" "(main)${_earl_name} Unknown error, should log"
                      ;;
             esac
             fi
          fi
       else
-         logger -t "${_log_tag}" " - there are other hosts running this script"
+         logger -t "${_log_tag}" "(main)${_earl_name} - there are other hosts running this script"
          cd ${_lock_dirs}
          for _each_host in */; do                                             # loop through the hosts directories
             check_time "${_each_host}" || \
                if [[ "$?" -eq "14" ]]; then
-                  logger -t "${_log_tag}" "This processes is running too long on the '${_each_host}' - removing the lock directory and files inside. Host will clean this processes on own side at next cron!"
+                  logger -t "${_log_tag}" "(main)${_earl_name} This processes is running too long on the '${_each_host}' - removing the lock directory and files inside. Host will clean this processes on own side at next cron!"
                   rm -f "${_each_host}/"*               # remove all files, the selection of just 'time' and 'pid' could make issues
                                                         # if some other files would appear - like .nfsXXX .tmp or similar
                   rmdir "${_each_host}/"
                fi
          done
-         logger -t "${_log_tag}" " - removing our host from the race and exit ... "
+         logger -t "${_log_tag}" "(main)${_earl_name} - removing our host from the race and exit ... "
          test -d ${_hostname} && rmdir ${_hostname}
          exit 0
       fi
    fi
+   remove_locks
 }
 
 {% endraw %}
@@ -225,12 +221,12 @@ declare earl_servers=(
 {%- endfor %}
 )
 {% raw %}
+logger -t "${_log_tag}" "___ Starting ___"
 for _each_server in "${earl_servers[@]}"; do
-   ( sleep $((RANDOM % _small_delay))  # small random delay, just in case if two systems would run the cron at the same time
-   _earl_name="${_each_server}"
+   ( _earl_name="${_each_server}"
    start_flow
    ) 1>/dev/null 2>&1 &                # sent to background, so that if one node fails, others can finish normally
+   wait
 done
-wait
 {% endraw %}
 {% endif %}
